### ISSUE TITLE
python plotting does not work on windows

### ISSUE THREAD

**Issue by azuendorf** [tecan/ttc21incrementalLabWorkflows#1]
Hi, running the reference solution I get an error in the plotting phase. See below. 
I use python 3.9

Printing diagram for scenario = scale_samples, phase = Initial
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\matplotlib\axis.py", line 1500, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "C:\Python39\lib\site-packages\matplotlib\category.py", line 49, in convert
    raise ValueError(
ValueError: Missing category information for StrCategoryConverter; this might be caused by unintendedly mixing categorical and numeric data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zuend\IdeaProjects\TTC2021LabWorkflow\ttc21incrementalLabWorkflows\scripts\run.py", line 167, in <module>
    visualize(config)
  File "C:\Users\zuend\IdeaProjects\TTC2021LabWorkflow\ttc21incrementalLabWorkflows\scripts\run.py", line 125, in visualize
    _visualize(scenario.Name, timesForScenario, 'Time', 'ms', 0.000001)
  File "C:\Users\zuend\IdeaProjects\TTC2021LabWorkflow\ttc21incrementalLabWorkflows\scripts\run.py", line 104, in _visualize
    plot = results.plot(logx=True,xticks=sizes)
  File "C:\Python39\lib\site-packages\pandas\plotting\_core.py", line 955, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "C:\Python39\lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 61, in plot
    plot_obj.generate()
  File "C:\Python39\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 283, in generate
    self._adorn_subplots()
  File "C:\Python39\lib\site-packages\pandas\plotting\_matplotlib\core.py", line 500, in _adorn_subplots
    ax.set_xticks(self.xticks)
  File "C:\Python39\lib\site-packages\matplotlib\axes\_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "C:\Python39\lib\site-packages\matplotlib\axis.py", line 1814, in set_ticks
    ticks = self.convert_units(ticks)
  File "C:\Python39\lib\site-packages\matplotlib\axis.py", line 1502, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: array(['1', '16', '2', '32', '4', '8'], dtype=object)

C:\Users\zuend\IdeaProjects\TTC2021LabWorkflow\ttc21incrementalLabWorkflows>

**Comment by azuendorf** [comment]
my reporting.json is: 

{
  "Dimensions": {
    "X_Dimensions": {
      "Size": true,
      "Iteration": true
    },
    "Groups": {
      "Query": true,
      "Tool": true
    }
  },
  "Summarize_Functions": [
    {
      "Phases": [
        "check",
        "transformation"
      ],
      "Metric": "time",
      "Y_Label": "Time (ms)",
      "Y_Axis_Scale": -6
    },
    {
      "Phases": [
        "result"
      ],
      "Metric": "scalar",
      "Y_Label": "Invalid elements",
      "Y_Axis_Scale": 0
    }
  ],
  "Extension": ["png", "pdf"]
}

**Comment by georghinkel** [comment]
The reporting.json is ignored now since I changed the plotting from R to Python in order to reduce dependencies (and because I had some trouble with R, lately). The problem here is that I cannot reproduce, with Python Anaconda 3.7.4, everything is good.

The problem seems to be that it is not picking up the right data type and thinks that the size row is objects. I will see whether I can fix this.

**Comment by georghinkel** [comment]
What versions of matplotlib and pandas do you have? I have 3.1.1 and 0.25.1, respectively. Could it be that you output the model sizes in quotes? I believe this would make pandas think that the data is categorial. Without quotes, I see no reason that pandas should declare it as objects.

**Comment by azuendorf** [comment]
Well, this seems to be a blody windows problem. Could you by any chance provide a docker container with a running installation that I could use?
