### ISSUE TITLE
Reference solution fails for scale_samples models greater equal 64

### ISSUE THREAD

**Issue by azuendorf** [tecan/ttc21incrementalLabWorkflows#3]
Running the Reference solution on scale_samples 1, 2, 4, 8, 16, 32 works just fine, the greater examples fail with: 

Program exited with errorCalledProcessError(1, 'dotnet bin/netcoreapp3.1/NMFSolution.dll reference')
Running benchmark: tool = Reference, scenario = scale_samples, model = 256
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\zuend\IdeaProjects\TTC2021LabWorkflow\ttc21incrementalLabWorkflows\models\scale_samples\256\results\initialResult-Reference.xmi'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at TTC2021.LabWorkflows.Commandline.SolveVerbBase.Initial() in C:\Projects\ttc2021\solutions\Reference\Commandline\SolveVerbBase.cs:line 74
   at TTC2021.LabWorkflows.Commandline.SolveVerbBase.ExecuteCore() in C:\Projects\ttc2021\solutions\Reference\Commandline\SolveVerbBase.cs:line 36
   at TTC2021.LabWorkflows.Commandline.VerbBase.Execute() in C:\Projects\ttc2021\solutions\Reference\Commandline\VerbBase.cs:line 15

**Comment by georghinkel** [comment]
I will take a look into that.

**Comment by azuendorf** [comment]
For some reasons this works now. Perhabs I did not have the latest version. So Issue solved.
